language: python
sudo: required
before_script:
  - sudo add-apt-repository ppa:chris-lea/libsodium -y
  - sudo apt-get -qq update
  - sudo apt-get install libsodium13 -y
python:
  - "2.7"
services:
  - couchdb
env:
  global:
    - TZ=Europe/Kiev

cache:
  directories:
    - eggs
before_install:
  - pip install setuptools==38.5.0
  - python2 bootstrap.py
install:
  - bin/buildout -N
script:
  - bin/python run_tests.py
after_success:
  - bin/coveralls

